var $chairBase = document.querySelector('.chair-base')
var $chairLeg1 = document.querySelector('.chair-leg-1')
var $chairLeg2 = document.querySelector('.chair-leg-2')
var $chairLeg3 = document.querySelector('.chair-leg-3')
var $chairLeg4 = document.querySelector('.chair-leg-4')
var $chairLeg5 = document.querySelector('.chair-leg-5')
var $chairWheel1 = document.querySelector('.chair-wheel-1')
var $chairWheel2 = document.querySelector('.chair-wheel-2')
var $chairWheel3 = document.querySelector('.chair-wheel-3')
var $chairWheel4 = document.querySelector('.chair-wheel-4')
var $chairWheel5 = document.querySelector('.chair-wheel-5')
var $chairSeat = document.querySelector('.chair-seat')
var $chairBack = document.querySelector('.chair-back')
var $chairArmrest1 = document.querySelector('.chair-armrest-1')
var $chairArmrest2 = document.querySelector('.chair-armrest-2')

create3DNode($chairBase)
create3DNode($chairLeg1)
create3DNode($chairLeg2)
create3DNode($chairLeg3)
create3DNode($chairLeg4)
create3DNode($chairLeg5)
create3DNode($chairWheel1)
create3DNode($chairWheel2)
create3DNode($chairWheel3)
create3DNode($chairWheel4)
create3DNode($chairWheel5)
create3DNode($chairSeat)
create3DNode($chairBack)
create3DNode($chairArmrest1)
create3DNode($chairArmrest2)
