var $floor = document.querySelector('.floor')
var $floorCarpet = document.querySelector('.floor-carpet')
var $wall1Part1 = document.querySelector('.wall-1__part-1')
var $wall1Part2 = document.querySelector('.wall-1__part-2')
var $wall2 = document.querySelector('.wall-2')
var $wall3Part1 = document.querySelector('.wall-3__part-1')
var $wall3Part2 = document.querySelector('.wall-3__part-2')
var $wall3Part3 = document.querySelector('.wall-3__part-3')
var $wall3Part4 = document.querySelector('.wall-3__part-4')
var $roof1 = document.querySelector('.roof-1')
var $roof2 = document.querySelector('.roof-2')
var $wall4 = document.querySelector('.wall-4')
var $wall4Picture1 = document.querySelector('.wall-4_picture-1')
var $wall4Picture2 = document.querySelector('.wall-4_picture-2')
var $wall4Picture3 = document.querySelector('.wall-4_picture-3')

create3DNode($floor)
create3DNode($floorCarpet)
create3DNode($wall1Part1)
create3DNode($wall1Part2)
create3DNode($wall2)
create3DNode($wall3Part1)
create3DNode($wall3Part2)
create3DNode($wall3Part3)
create3DNode($wall3Part4)
create3DNode($roof1)
create3DNode($roof2)
create3DNode($wall4)
create3DNode($wall4Picture1)
create3DNode($wall4Picture2)
create3DNode($wall4Picture3)
