var $windowFrame1 = document.querySelector('.window-frame-1')
var $windowFrame2 = document.querySelector('.window-frame-2')
var $windowFrame3 = document.querySelector('.window-frame-3')
var $windowFrame4 = document.querySelector('.window-frame-4')
var $windowSubframe1 = document.querySelector('.window-subframe-1')
var $windowSubframe2 = document.querySelector('.window-subframe-2')
var $windowSubframe3 = document.querySelector('.window-subframe-3')
var $windowSubframe4 = document.querySelector('.window-subframe-4')
var $windowSubframe5 = document.querySelector('.window-subframe-5')
var $windowSubframe6 = document.querySelector('.window-subframe-6')
var $windowSubframe7 = document.querySelector('.window-subframe-7')
var $windowSubframe8 = document.querySelector('.window-subframe-8')
var $windowGlass1 = document.querySelector('.window-glass-1')
var $windowGlass2 = document.querySelector('.window-glass-2')

create3DNode($windowFrame1)
create3DNode($windowFrame2)
create3DNode($windowFrame3)
create3DNode($windowFrame4)
create3DNode($windowSubframe1)
create3DNode($windowSubframe2)
create3DNode($windowSubframe3)
create3DNode($windowSubframe4)
create3DNode($windowSubframe5)
create3DNode($windowSubframe6)
create3DNode($windowSubframe7)
create3DNode($windowSubframe8)
create3DNode($windowGlass1)
create3DNode($windowGlass2)
